spring:
  kafka:
    bootstrap-servers: localhost:9092
    security:
      protocol: PLAINTEXT
    consumer:
      group-id: ronin-detector
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: '*'
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 30

  data:
    redis:
      host: localhost
      port: 6379

kafka:
  transaction:
    topic: ronin-transactions
    concurrency: 3
  test:
    topic: ronin-test